# Generated by Django 5.1.4 on 2024-12-30 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Darbuotojas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("vardas", models.CharField(max_length=100, verbose_name="Vardas")),
                ("pavarde", models.CharField(max_length=100, verbose_name="Pavarde")),
                ("pareigos", models.CharField(max_length=100, verbose_name="Pareigos")),
            ],
            options={
                "verbose_name": "Darbuotojas",
                "verbose_name_plural": "Darbuotojai",
            },
        ),
        migrations.CreateModel(
            name="Klientas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pavadinimas",
                    models.CharField(max_length=250, verbose_name="Pavadinimas"),
                ),
                ("adresas", models.CharField(max_length=100, verbose_name="Adresas")),
                (
                    "telefono_numeris",
                    models.CharField(max_length=20, verbose_name="Telefono numeris"),
                ),
                (
                    "elektroninis_pastas",
                    models.CharField(
                        max_length=100, verbose_name="Elektroninis pastas"
                    ),
                ),
                (
                    "kontaktinis_asmuo",
                    models.CharField(max_length=100, verbose_name="Kontaktinis asmuo"),
                ),
                (
                    "saskaitos_numeris",
                    models.CharField(max_length=25, verbose_name="Saskaitos numeris"),
                ),
            ],
            options={
                "verbose_name": "Klientas",
                "verbose_name_plural": "Klientai",
            },
        ),
        migrations.CreateModel(
            name="KontaktinisAsmuo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vardas", models.CharField(max_length=100, verbose_name="Vardas")),
                ("pareigos", models.CharField(max_length=100, verbose_name="Pareigos")),
                (
                    "telefono_numeris",
                    models.CharField(max_length=20, verbose_name="Telefono numeris"),
                ),
                (
                    "elektroninis_pastas",
                    models.CharField(
                        max_length=100, verbose_name="Elektroninis pastas"
                    ),
                ),
                (
                    "klientas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice_management.klientas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontaktinis asmuo",
                "verbose_name_plural": "Kontaktiniai asmenys",
            },
        ),
        migrations.CreateModel(
            name="Saskaita",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("ivedimo_data", models.DateTimeField(auto_now_add=True)),
                (
                    "apmokejimo_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Apmokejimo data"
                    ),
                ),
                (
                    "suma",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Suma"
                    ),
                ),
                (
                    "statusas",
                    models.CharField(
                        choices=[
                            ("israsyta", "Israsyta"),
                            ("apmoketa", "Apmoketa"),
                            ("pradelsta", "Pradelsta"),
                        ],
                        default="israsyta",
                        max_length=20,
                    ),
                ),
                (
                    "klientas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice_management.klientas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saskaita",
                "verbose_name_plural": "Saskaitos",
            },
        ),
    ]
