# Generated by Django 5.1.4 on 2024-12-30 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="klientas",
            name="ivedimo_data",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
