# Generated by Django 5.1.4 on 2025-01-07 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_management", "0002_klientas_ivedimo_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="Contact Person"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=25, verbose_name="Account Number"),
                ),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice_management.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("payed", "Payed"),
                            ("overdue", "Overdue"),
                        ],
                        default="israsyta",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice_management.client",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Darbuotojas",
        ),
        migrations.RemoveField(
            model_name="saskaita",
            name="klientas",
        ),
        migrations.DeleteModel(
            name="KontaktinisAsmuo",
        ),
        migrations.DeleteModel(
            name="Klientas",
        ),
        migrations.DeleteModel(
            name="Saskaita",
        ),
    ]
