# Generated by Django 5.1.4 on 2025-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_management", "0003_client_contactperson_employer_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("payed", "Payed"),
                    ("overdue", "Overdue"),
                ],
                default="issued",
                max_length=20,
            ),
        ),
    ]
