# Generated by Django 5.1.4 on 2025-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_management", "0004_invoice_reminder_sent_alter_client_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                ],
                default="issued",
                max_length=20,
            ),
        ),
    ]
