# Generated by Django 5.1.3 on 2025-01-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_management", "0006_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
